# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4dce6d89f4931401b02737ae63e417d1d046015769ad8b73fba49b02948d7dd36c05c5d11869aef4059c1534eda2839dad6ea0a08f6f24405c73b9913f0bcf09

test:
  secret_key_base: e6575764a76472e4f3a1919ce092b957ebc36bf02d2d0048e78a92ab596b3485895db39ef7da58ef958d9d3579ab63570da0e994846e57a3f845c7df3347989a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
